name: Running npm build 
on: push
jobs:
  Test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
            node-version : 18
      - name: Install Dependency
        run: npm ci
      - name: Run test
        run: npm test
  Build-job:
    needs: Test-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
            node-version : 18
      - name: Install Dependency
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: Dist-files
            path: dist     
  Deploy-job:
    needs: Build-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying.."               